services:
  - type: web
    name: hyperionx
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
